"""added credits column in user

Revision ID: 5f4831cfbba1
Revises: bdf05c847251
Create Date: 2024-11-30 17:48:38.720929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f4831cfbba1'
down_revision = 'bdf05c847251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used_credits', sa.SmallInteger(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('used_credits')

    # ### end Alembic commands ###
