"""major migration

Revision ID: 92d06fa5f827
Revises: ec1d8c6059c3
Create Date: 2024-11-16 17:53:15.563084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92d06fa5f827'
down_revision = 'ec1d8c6059c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_collections_name', ['collection_name'])
        batch_op.drop_constraint('collection_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user_articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('uq_collections_name', type_='foreignkey')
        batch_op.drop_column('saved_at')
        batch_op.drop_column('collection_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collection_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('saved_at', sa.DATETIME(), nullable=True))
        batch_op.create_foreign_key(None, 'collections', ['collection_id'], ['id'])
        batch_op.drop_column('id')

    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('collection_user_id', 'users', ['user_id'], ['id'])
        batch_op.drop_constraint('uq_collections_name', type_='unique')

    # ### end Alembic commands ###
