"""added credits column in user

Revision ID: e9ca6dd28529
Revises: 5f4831cfbba1
Create Date: 2024-11-30 17:51:29.709010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9ca6dd28529'
down_revision = '5f4831cfbba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used_credits', sa.SmallInteger(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('used_credits')

    # ### end Alembic commands ###
